### ISSUE TITLE
Unable to create table for class, Are you missing @Table annotation?

### ISSUE THREAD

**Issue by mradzinski** [pieces029/shillelagh#23]
Weirdly enough, the model does have the `Table` annotation...

    @Table
    public class TestModel {
        @Id(name = Constants.COLUMN_ID)
        public long _id;

        @Column(name = Constants.COLUMN_TEST)
        public String testColumn;

        public TestModel (String testColumn) {
            this.testColumn = testColumn;
        }
    }

The above error is followed by this one on the Logcat trace:
`Caused by: java.lang.ClassNotFoundException: com.tests.shillelagh.models.TestModel$$Shillelagh`

Looks to me the annotation processor is having some issues...

**Comment by pieces029** [comment]
Are you using progaurd?

**Comment by mradzinski** [comment]
Never mind, I copied the gradle imports from your readme and they are wrong, you missed the processor. Check the provided dependency.

**Comment by pieces029** [comment]
Oh, good catch. I'll update as soon as I get time.

**Comment by mradzinski** [comment]
No problemo! I just tested and now that I added the processor it works. Cheers!

**Comment by pieces029** [comment]
Fixed the docs. @mradzinski Thanks!
